# Generated by Django 4.2.5 on 2023-09-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='paid_course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='paid_lesson',
            new_name='lesson',
        ),
        migrations.AddField(
            model_name='payments',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='статус оплаты'),
        ),
        migrations.AddField(
            model_name='payments',
            name='session',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='сессия для оплаты'),
        ),
    ]
