# Generated by Django 4.2.5 on 2023-09-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_paid_course_payments_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date_payment',
            field=models.DateField(blank=True, null=True, verbose_name='дата платежа'),
        ),
    ]
