# Generated by Django 4.2.5 on 2023-09-30 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_subscribe_update_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='последняя дата обновления'),
        ),
    ]
