# Generated by Django 4.2.5 on 2023-09-30 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0006_remove_subscribe_update_course_and_more'),
        ('subscribes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_update_course', models.BooleanField(blank=True, null=True, verbose_name='подписка на обновления курса')),
                ('is_update_lesson', models.BooleanField(blank=True, null=True, verbose_name='подписка на обновления урок')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='ссылка на курс')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.lesson', verbose_name='ссылка на урок')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'подписка на обновления',
                'verbose_name_plural': 'подписки на обновления',
            },
        ),
        migrations.DeleteModel(
            name='Subscribe_update',
        ),
    ]
