# Generated by Django 4.2.5 on 2023-09-30 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_subscribe_update_course_and_more'),
        ('subscribes', '0002_subscribeupdate_delete_subscribe_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribeupdate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribe', to='course.course', verbose_name='ссылка на курс'),
        ),
        migrations.AlterField(
            model_name='subscribeupdate',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribe', to='course.lesson', verbose_name='ссылка на урок'),
        ),
    ]
